# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗██████╗ ██╗     ███████╗
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║██╔══██╗██║     ██╔════╝
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║██║  ██║██║     █████╗  
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║██║  ██║██║     ██╔══╝  
# ██║  ██║   ██║   ██║     ██║  ██║██║██████╔╝███████╗███████╗
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚═╝╚═════╝ ╚══════╝╚══════╝
                           
general {
    lock_cmd = ~/.local/share/quickshell-lockscreen/lock.sh
    before_sleep_cmd = ~/.local/share/quickshell-lockscreen/lock.sh
    after_sleep_cmd = hyprctl dispatch dpms on
}

#listener {
#    timeout = 150                                             # 2.5min
#}

listener {
    timeout = 600                      # 10min
    on-timeout = ~/.local/share/quickshell-lockscreen/lock.sh # lock screen when timeout has passed
}

listener {
    timeout = 630                                            # 10.5min
    on-timeout = hyprctl dispatch dpms off                   # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen on when activity is detected
}
